name: ShopNow Security Pipeline

on:
  push:
    branches:
      - main
      - sprint1
      - sprint2

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker
        run: docker --version

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.65.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.65.0_Linux-64bit.deb

      - name: Verify Trivy
        run: trivy --version

      - name: Make Scripts Executable
        run: |
          chmod +x scripts/build.sh
          chmod +x scripts/scan.sh

      - name: Build Docker Images
        run: ./scripts/build.sh

      - name: Run Security Scan
        run: ./scripts/scan.sh

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-reports
          path: reports/