name: ShopNow Security Pipeline

on:
  push:
    branches:
      - main
      - sprint1
      - sprint2
      - sprint3
      - sprint4-Dashboard
      - sprint5
      - sprint6

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker
        run: docker --version

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Verify Trivy
        run: trivy --version

      - name: Make Scripts Executable
        run: |
          chmod +x scripts/build.sh
          chmod +x scripts/scan.sh

      - name: Build Docker Images
        run: ./scripts/build.sh

      - name: Run Security Scan
        run: ./scripts/scan.sh

      - name: Run Exception Handler
        run: python scripts/exception_handler.py

      - name: Compare Reports
        run: python scripts/compare_reports.py

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sprint6-security-reports
          path: reports/